import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '入门',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/getting-started',
        title: '入门',
        description: '安装、快速上手与支持的平台版本。',
      },
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: '使用指南',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/guides',
        title: '使用指南',
        description: '面向日常开发的任务导向教程。',
      },
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: '核心概念',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/concepts',
        title: '核心概念',
        description: '理解 ZLua 的设计模型与运行时架构。',
      },
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'API 参考',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/reference',
        title: 'API 参考',
        description: 'C# 特性、Lua API 与编组速查。',
      },
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: '规范文档',
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/category/spec',
        title: '规范文档',
        description: '权威语义规范，供进阶开发者与贡献者查阅。',
      },
      items: [{type: 'autogenerated', dirName: 'spec'}],
    },
    {
      type: 'category',
      label: '社区',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/community',
        title: '社区',
        description: '路线图、测试、FAQ 与联系方式。',
      },
      items: [{type: 'autogenerated', dirName: 'community'}],
    },
  ],

  architectureSidebar: [
    {
      type: 'category',
      label: '架构与性能',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/architecture',
        title: '架构与性能',
        description: 'Il2Cpp 实现、调用路径与性能分析。',
      },
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
  ],
};

export default sidebars;
