import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '入门',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/getting-started',
        title: '入门',
        description: '安装、快速上手与支持的平台版本。',
      },
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: '使用指南',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/guides',
        title: '使用指南',
        description: '循序渐进：安装 → 互调 → 构建 → 日常用法 → 高级 Marshal → 迁移。',
      },
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: '核心概念',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/concepts',
        title: '核心概念',
        description: '设计模型、术语与选型摘要。',
      },
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: '选型对比',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/compare',
        title: '选型对比',
        description: '与 xLua / toLua / SLua 的特性、性能、GC 与桥体积对比（非行为契约）。',
      },
      items: [{type: 'autogenerated', dirName: 'compare'}],
    },
    {
      type: 'category',
      label: 'API 参考',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/reference',
        title: 'API 参考',
        description: 'C# 特性、Lua API 与 Marshal 速查。',
      },
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: '规范文档',
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/category/spec',
        title: '规范文档',
        description: '权威语义规范（本仓库 docs/spec 为唯一标准）。',
      },
      items: [{type: 'autogenerated', dirName: 'spec'}],
    },
    {
      type: 'category',
      label: '社区',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/community',
        title: '社区',
        description: '路线图、测试、FAQ、迁移与联系方式。',
      },
      items: [{type: 'autogenerated', dirName: 'community'}],
    },
  ],

  architectureSidebar: [
    {
      type: 'category',
      label: '架构与实现',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/impl',
        title: '架构与实现',
        description: 'Mono / Il2Cpp 实现对照（不覆盖 spec）。',
      },
      items: [{type: 'autogenerated', dirName: 'impl'}],
    },
  ],
};

export default sidebars;
